// generated by fakerjsgenerator
///
module faked.faker_en_ie;

import faked.base;


///
class Faker_en_ie : Faker {
@safe:
	import std.random;
	import std.array;
	import std.format;
	import std.conv : to;

	///
	this(int seed) {
        super(seed);
	}

	///
	override string addressDefaultCountry() {
		auto data = [
		"Ireland'"
		];
		return choice(data, this.rnd);
	}

	///
	override string addressCounty() {
		auto data = [
		"Carlow",
		"Cavan",
		"Clare",
		"Cork",
		"Donegal",
		"Dublin",
		"Galway",
		"Kerry",
		"Kildare",
		"Kilkenny",
		"Laois",
		"Leitrim",
		"Limerick",
		"Longford",
		"Louth",
		"Mayo",
		"Meath",
		"Monaghan",
		"Offaly",
		"Roscommon",
		"Sligo",
		"Tipperary",
		"Waterford",
		"Westmeath",
		"Wexford",
		"Wicklow",
		""
		];
		return choice(data, this.rnd);
	}

	///
	override string internetDomainSuffix() {
		auto data = [
		"ie', 'com', 'net', 'info', 'eu'"
		];
		return choice(data, this.rnd);
	}

}
