// generated by fakerjsgenerator
///
module faked.faker_zh_tw;

import faked.base;


///
class Faker_zh_tw : Faker {
@safe:
	import std.random;
	import std.array;
	import std.format;
	import std.conv : to;

	///
	this(int seed) {
        super(seed);
	}

	///
	override string phoneNumberFormats() {
		auto data = [
		"0#-#######",
		"02-########",
		"09##-######'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationStateAbbr() {
		auto data = [
		"北",
		"新北",
		"桃",
		"中",
		"南",
		"高",
		"基",
		"竹市",
		"嘉市",
		"竹縣",
		"苗",
		"彰",
		"投",
		"雲",
		"嘉縣",
		"宜",
		"花",
		"東",
		"澎",
		"金",
		"馬"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationState() {
		auto data = [
		"福建省",
		"台灣省'"
		];
		return choice(data, this.rnd);
	}


	override string locationStreetPattern() {
		final switch(uniform(0, 1, this.rnd)) {
			case 0: return personLastName() ~ locationStreetSuffix() ~ "'";
		}
	}


	override string locationStreetAddress() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "normal: '" ~ locationStreet() ~ locationBuildingNumber() ~ "號";
			case 1: return "full: '" ~ locationStreet() ~ locationBuildingNumber() ~ "號 " ~ locationSecondaryAddress();
		}
	}

	///
	override string locationDefaultCountry() {
		auto data = [
		"Taiwan (R.O.C.)'"
		];
		return choice(data, this.rnd);
	}


	override string locationCityPattern() {
		final switch(uniform(0, 1, this.rnd)) {
			case 0: return locationCityPrefix() ~ locationCitySuffix() ~ "'";
		}
	}

	///
	override string locationCitySuffix() {
		auto data = [
		"縣",
		"市'"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationCityPrefix() {
		auto data = [
		"臺北",
		"新北",
		"桃園",
		"臺中",
		"臺南",
		"高雄",
		"基隆",
		"新竹",
		"嘉義",
		"苗栗",
		"彰化",
		"南投",
		"雲林",
		"屏東",
		"宜蘭",
		"花蓮",
		"臺東",
		"澎湖",
		"金門",
		"連江"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationBuildingNumber() {
		auto data = [
		"####",
		"###",
		"##",
		"#'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationPostcode() {
		auto data = [
		"######'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationStreetSuffix() {
		auto data = [
		"街",
		"路",
		"北路",
		"南路",
		"東路",
		"西路'"
		];
		return choice(data, this.rnd);
	}

	///
	override string colorHuman() {
		auto data = [
		"紅色",
		"綠色",
		"藍色",
		"黃色",
		"紫色",
		"薄荷綠色",
		"藍綠色",
		"白色",
		"黑色",
		"橙色",
		"粉紅色",
		"灰色",
		"紅褐色",
		"藍紫色",
		"青綠色",
		"棕褐色",
		"天藍色",
		"淺橙色",
		"紫紅色",
		"淡紫色",
		"淡褐色",
		"青檸色",
		"乳白色",
		"靛藍色",
		"金色",
		"銀色"
		];
		return choice(data, this.rnd);
	}

	///
	override string dateWeekday() {
		auto data = [
		"wide: ['星期天",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六']",
		"abbr: ['週日",
		"週一",
		"週二",
		"週三",
		"週四",
		"週五",
		"週六']"
		];
		return choice(data, this.rnd);
	}


	override string dateMonth() {
		final switch(uniform(0, 28, this.rnd)) {
			case 0: return "wide: [";
			case 1: return "1月";
			case 2: return "2月";
			case 3: return "3月";
			case 4: return "4月";
			case 5: return "5月";
			case 6: return "6月";
			case 7: return "7月";
			case 8: return "8月";
			case 9: return "9月";
			case 10: return "10月";
			case 11: return "11月";
			case 12: return "12月";
			case 13: return "]";
			case 14: return "abbr: [";
			case 15: return "1月";
			case 16: return "2月";
			case 17: return "3月";
			case 18: return "4月";
			case 19: return "5月";
			case 20: return "6月";
			case 21: return "7月";
			case 22: return "8月";
			case 23: return "9月";
			case 24: return "10月";
			case 25: return "11月";
			case 26: return "12月";
			case 27: return "]";
		}
	}

	///
	override string personMaleFirstName() {
		auto data = [
		"修傑",
		"修潔",
		"偉宸",
		"偉澤",
		"偉祺",
		"偉誠",
		"健柏",
		"健雄",
		"博文",
		"博超",
		"君浩",
		"哲瀚",
		"嘉熙",
		"天宇",
		"天磊",
		"天翊",
		"子軒",
		"展鵬",
		"峻熙",
		"建輝",
		"弘文",
		"志強",
		"志澤",
		"思源",
		"思聰",
		"思遠",
		"振家",
		"擎宇",
		"文博",
		"文昊",
		"文軒",
		"昊天",
		"昊強",
		"昊然",
		"明哲",
		"明杰",
		"明軒",
		"明輝",
		"晉鵬",
		"智輝",
		"梓晨",
		"榮軒",
		"正豪",
		"浩宇",
		"浩然",
		"浩軒",
		"澤洋",
		"炎彬",
		"燁偉",
		"瑞霖",
		"皓軒",
		"立果",
		"立誠",
		"立輝",
		"紹輝",
		"紹齊",
		"耀傑",
		"胤祥",
		"致遠",
		"語堂",
		"越澤",
		"遠航",
		"金鑫",
		"鑫磊",
		"鑫鵬",
		"雨澤",
		"雪松",
		"鴻濤",
		"鴻煊",
		"鵬濤",
		"鵬煊",
		"鵬飛"
		];
		return choice(data, this.rnd);
	}

	///
	override string personLastName() {
		auto data = [
		"王",
		"李",
		"張",
		"劉",
		"陳",
		"楊",
		"黃",
		"吳",
		"趙",
		"週",
		"徐",
		"孫",
		"馬",
		"朱",
		"胡",
		"林",
		"郭",
		"何",
		"高",
		"羅",
		"鄭",
		"梁",
		"謝",
		"宋",
		"唐",
		"許",
		"鄧",
		"馮",
		"韓",
		"曹",
		"曾",
		"彭",
		"蕭",
		"蔡",
		"潘",
		"田",
		"董",
		"袁",
		"於",
		"餘",
		"葉",
		"蔣",
		"杜",
		"蘇",
		"魏",
		"程",
		"呂",
		"丁",
		"沈",
		"任",
		"姚",
		"盧",
		"傅",
		"鐘",
		"姜",
		"崔",
		"譚",
		"廖",
		"範",
		"汪",
		"陸",
		"金",
		"石",
		"戴",
		"賈",
		"韋",
		"夏",
		"邱",
		"方",
		"侯",
		"鄒",
		"熊",
		"孟",
		"秦",
		"白",
		"江",
		"閻",
		"薛",
		"尹",
		"段",
		"雷",
		"黎",
		"史",
		"龍",
		"陶",
		"賀",
		"顧",
		"毛",
		"郝",
		"龔",
		"邵",
		"萬",
		"錢",
		"嚴",
		"賴",
		"覃",
		"洪",
		"武",
		"莫",
		"孔"
		];
		return choice(data, this.rnd);
	}


	override string personName() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "{ value: '" ~ personLastName() ~ personFirstName();
			case 1: return "weight: 1 }";
		}
	}

	///
	override string personFemaleFirstName() {
		auto data = [
		"俊馳",
		"凱瑞",
		"博濤",
		"嘉懿",
		"子涵",
		"子騫",
		"子默",
		"思淼",
		"懿軒",
		"擎蒼",
		"旭堯",
		"昊焱",
		"晟睿",
		"智宸",
		"智淵",
		"曉博",
		"曉嘯",
		"楷瑞",
		"樂駒",
		"瀟然",
		"炫明",
		"煜城",
		"煜祺",
		"熠彤",
		"燁磊",
		"燁華",
		"燁霖",
		"瑾瑜",
		"睿淵",
		"立軒",
		"笑愚",
		"聰健",
		"苑博",
		"越彬",
		"鈺軒",
		"錦程",
		"靖琪",
		"風華",
		"鶴軒",
		"鷺洋",
		"黎昕"
		];
		return choice(data, this.rnd);
	}


	override string personLastNamePattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "{ value: '" ~ personLastName();
			case 1: return "weight: 1 }";
		}
	}

}
