// generated by fakerjsgenerator
///
module faked.faker_az;

import faked.base;


///
class Faker_az : Faker {
@safe:
	import std.random;
	import std.array;
	import std.format;
	import std.conv : to;

	///
	this(int seed) {
        super(seed);
	}

	///
	override string locationCityName() {
		auto data = [
		"Ağcabədi",
		"Ağdam",
		"Ağdaş",
		"Ağdərə",
		"Ağstafa",
		"Ağsu",
		"Astara",
		"Bakı",
		"Balakən",
		"Beyləqan",
		"Bərdə",
		"Biləsuvar",
		"Cəbrayıl",
		"Cəlilabad",
		"Culfa",
		"Daşkəsən",
		"Dəliməmmədli",
		"Füzuli",
		"Gədəbəy",
		"Gəncə",
		"Goranboy",
		"Göyçay",
		"Göygöl",
		"Göytəpə",
		"Hacıqabul",
		"Horadiz",
		"Xaçmaz",
		"Xankəndi",
		"Xocalı",
		"Xocavənd",
		"Xırdalan",
		"Xızı",
		"Xudat",
		"İmişli",
		"İsmayıllı",
		"Kəlbəcər",
		"Kürdəmir",
		"Qax",
		"Qazax",
		"Qəbələ",
		"Qobustan",
		"Qovlar",
		"Quba",
		"Qubadlı",
		"Qusar",
		"Laçın",
		"Lerik",
		"Lənkəran",
		"Liman",
		"Masallı",
		"Mingəçevir",
		"Naftalan",
		"Naxçıvan (şəhər)",
		"Neftçala",
		"Oğuz",
		"Ordubad",
		"Saatlı",
		"Sabirabad",
		"Salyan",
		"Samux",
		"Siyəzən",
		"Sumqayıt",
		"Şabran",
		"Şahbuz",
		"Şamaxı",
		"Şəki",
		"Şəmkir",
		"Şərur",
		"Şirvan",
		"Şuşa",
		"Tərtər",
		"Tovuz",
		"Ucar",
		"Yardımlı",
		"Yevlax",
		"Zaqatala",
		"Zəngilan",
		"Zərdab"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationCountry() {
		auto data = [
		"Akrotiri və Dekeliya",
		"Aland adaları",
		"Albaniya",
		"Almaniya",
		"Amerika Samoası",
		"Andorra",
		"Angilya",
		"Anqola",
		"Antiqua və Barbuda",
		"Argentina",
		"Aruba",
		"Avstraliya",
		"Avstriya",
		"Azərbaycan",
		"Baham adaları",
		"Banqladeş",
		"Barbados",
		"Belçika",
		"Beliz",
		"Belarus",
		"Benin",
		"Bermud adaları",
		"BƏƏ",
		"ABŞ",
		"Boliviya",
		"Bolqarıstan",
		"Bosniya və Herseqovina",
		"Botsvana",
		"Böyük Britaniya",
		"Braziliya",
		"Bruney",
		"Burkina-Faso",
		"Burundi",
		"Butan",
		"Bəhreyn",
		"Cersi",
		"Cəbəli-Tariq",
		"CAR",
		"Cənubi Sudan",
		"Cənubi Koreya",
		"Cibuti",
		"Çad",
		"Çexiya",
		"Monteneqro",
		"Çili",
		"ÇXR",
		"Danimarka",
		"Dominika",
		"Dominikan Respublikası",
		"Efiopiya",
		"Ekvador",
		"Ekvatorial Qvineya",
		"Eritreya",
		"Ermənistan",
		"Estoniya",
		"Əfqanıstan",
		"Əlcəzair",
		"Farer adaları",
		"Fələstin Dövləti",
		"Fici",
		"Kot-d’İvuar",
		"Filippin",
		"Finlandiya",
		"Folklend adaları",
		"Fransa",
		"Fransa Polineziyası",
		"Gernsi",
		"Gürcüstan",
		"Haiti",
		"Hindistan",
		"Honduras",
		"Honkonq",
		"Xorvatiya",
		"İndoneziya",
		"İordaniya",
		"İraq",
		"İran",
		"İrlandiya",
		"İslandiya",
		"İspaniya",
		"İsrail",
		"İsveç",
		"İsveçrə",
		"İtaliya",
		"Kabo-Verde",
		"Kamboca",
		"Kamerun",
		"Kanada",
		"Kayman adaları",
		"Keniya",
		"Kipr",
		"Kiribati",
		"Kokos adaları",
		"Kolumbiya",
		"Komor adaları",
		"Konqo Respublikası",
		"KDR",
		"Kosovo",
		"Kosta-Rika",
		"Kuba",
		"Kuk adaları",
		"Küveyt",
		"Qabon",
		"Qambiya",
		"Qana",
		"Qətər",
		"Qayana",
		"Qazaxıstan",
		"Qərbi Sahara",
		"Qırğızıstan",
		"Qrenada",
		"Qrenlandiya",
		"Quam",
		"Qvatemala",
		"Qvineya",
		"Qvineya-Bisau",
		"Laos",
		"Latviya",
		"Lesoto",
		"Liberiya",
		"Litva",
		"Livan",
		"Liviya",
		"Lixtenşteyn",
		"Lüksemburq",
		"Macarıstan",
		"Madaqaskar",
		"Makao",
		"Makedoniya",
		"Malavi",
		"Malayziya",
		"Maldiv adaları",
		"Mali",
		"Malta",
		"Marşall adaları",
		"Mavriki",
		"Mavritaniya",
		"Mayotta",
		"Meksika",
		"Men adası",
		"Mərakeş",
		"MAR",
		"Mikroneziya",
		"Milad adası",
		"Misir",
		"Myanma",
		"Moldova",
		"Monako",
		"Monqolustan",
		"Montserrat",
		"Mozambik",
		"Müqəddəs Yelena",
		"Askenson və Tristan-da-Kunya adaları",
		"Namibiya",
		"Nauru",
		"Nepal",
		"Niderland",
		"Niderland Antil adaları",
		"Niger",
		"Nigeriya",
		"Nikaraqua",
		"Niue",
		"Norfolk adası",
		"Norveç",
		"Oman",
		"Özbəkistan",
		"Pakistan",
		"Palau",
		"Panama",
		"Papua-Yeni Qvineya",
		"Paraqvay",
		"Peru",
		"Pitkern adaları",
		"Polşa",
		"Portuqaliya",
		"Prednestroviya",
		"Puerto-Riko",
		"Ruanda",
		"Rumıniya",
		"Rusiya",
		"Salvador",
		"Samoa",
		"San-Marino",
		"San-Tome və Prinsipi",
		"Seneqal",
		"Sen-Bartelemi",
		"Sent-Kits və Nevis",
		"Sent-Lüsiya",
		"Sen-Marten",
		"Sen-Pyer və Mikelon",
		"Sent-Vinsent və Qrenadina",
		"Serbiya",
		"Seyşel adaları",
		"Səudiyyə Ərəbistanı",
		"Sinqapur",
		"Slovakiya",
		"Sloveniya",
		"Solomon adaları",
		"Somali",
		"Somalilend",
		"Sudan",
		"Surinam",
		"Suriya",
		"Svazilend",
		"Syerra-Leone",
		"Şərqi Timor",
		"Şimali Marian adaları",
		"Şpisbergen və Yan-Mayen",
		"Şri-Lanka",
		"Tacikistan",
		"Tanzaniya",
		"Tailand",
		"Çin Respublikası",
		"Törks və Kaykos adaları",
		"Tokelau",
		"Tonqa",
		"Toqo",
		"Trinidad və Tobaqo",
		"Tunis",
		"Tuvalu",
		"Türkiyə",
		"Türkmənistan",
		"Ukrayna",
		"Uollis və Futuna",
		"Uqanda",
		"Uruqvay",
		"Vanuatu",
		"Vatikan",
		"Venesuela",
		"Amerika Virgin adaları",
		"Britaniya Virgin adaları",
		"Vyetnam",
		"Yamayka",
		"Yaponiya",
		"Yeni Kaledoniya",
		"Yeni Zelandiya",
		"Yəmən",
		"Yunanıstan",
		"Zambiya",
		"Zimbabve"
		];
		return choice(data, this.rnd);
	}


	override string locationStreetPattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return locationStreetSuffix() ~ " " ~ locationStreetName();
			case 1: return locationStreetName() ~ " " ~ locationStreetSuffix();
		}
	}


	override string locationStreetAddress() {
		final switch(uniform(0, 4, this.rnd)) {
			case 0: return "normal: '" ~ locationStreet();
			case 1: return locationBuildingNumber();
			case 2: return "full: '" ~ locationStreet();
			case 3: return locationBuildingNumber() ~ " " ~ locationSecondaryAddress();
		}
	}

	///
	override string locationDefaultCountry() {
		auto data = [
		"Azərbaycan'"
		];
		return choice(data, this.rnd);
	}


	override string locationCityPattern() {
		final switch(uniform(0, 1, this.rnd)) {
			case 0: return locationCityName() ~ "'";
		}
	}

	///
	string locationStreetName() {
		auto data = [
		"Abbas Fətullayev",
		"Abbas Mirzə Şərifzadə",
		"Abbas Səhhət",
		"Abdulla Şaiq",
		"Afiyəddin Cəlilov",
		"Axundov",
		"Ağa Nemətulla",
		"Ağadadaş Qurbanov",
		"Akademik Həsən Əliyev",
		"Akademik Lətif İmanov",
		"Alı Mustafayev",
		"Almas İldırım",
		"Asəf Zeynallı",
		"Asif Əsədullayev",
		"Aşıq Alı",
		"Aşıq Ələsgər",
		"Azadlıq prospekti",
		"Bakıxanov",
		"Balababa Məcidov",
		"Balaəmi Dadaşov",
		"Behbud Şaxtantinski",
		"Bəkir Çobanzadə",
		"Bəsti Bağırova",
		"Bəşir Səfəroğlu",
		"Böyük Qala",
		"Cabir Əliyev",
		"Camal Hacıəliyev",
		"Cavadxan",
		"Cavanşir",
		"Ceyhun Səlimov",
		"Ceyhunbəy Hacıbəyli",
		"Cəbiyev",
		"Cəfər Xəndan",
		"Cəfər Cabbarlı",
		"Cəlal Qurbanov",
		"Cəlil Məmmədquluzadə",
		"Çingiz Mustafayev",
		"Çobanzadə",
		"Dadaş Bünyadzadə",
		"Dağlı Yunus",
		"Dilarə Əliyeva",
		"Elçin Əzimov",
		"Eldar və Abdulla Əlibəyovlar",
		"Elxan Həsənov",
		"Elşən Mehdiyev",
		"Elşən Süleymanov",
		"Etibar Bəkirov",
		"Əbdüləzəl Dəmirçizadə",
		"Əbdülhəsən Anaplı",
		"Əbdülkərim Əlizadə",
		"Əhməd bəy Ağaoğlu",
		"Əhməd Cavad",
		"Əhməd Cəmil",
		"Əhməd Mehbalıyev",
		"Əhməd Rəcəbli",
		"Əjdər Xanbabayev",
		"Əkrəm Cəfərov",
		"Ələsgər Qayıbov",
		"Əliağa Vahid",
		"Əli Bəy Hüseynzadə",
		"Əlimərdan bəy Topçubaşov",
		"Əliyar Əliyev",
		"Əlövsət Abdulrəhimov",
		"Əlövsət Quliyev",
		"Əmir Bağırov",
		"Əsəd Əhmədov",
		"Əşrəf Yunusov",
		"Əzim Əzimzadə",
		"Əziz Əliyev",
		"Heybət Heybətov",
		"Həqiqət Rzayeva",
		"Həmid Araslı",
		"Hənifə Ələsgərova",
		"Hərbçilər",
		"Həsənoğu",
		"Həsən Seyidbəyli",
		"Hətəm Allahverdiyev",
		"Həzi Aslanov",
		"Hüsü Hacıyev",
		"Hüseynqulu Sarabski",
		"Fətəli xan Xoyski",
		"Fəzail Bayramov",
		"Fikrət Əmirov",
		"Fuad İbrahimbəyov",
		"Fuad Yusifov",
		"General Əliağa Şıxlinski",
		"Gülayə Qədirbəyova",
		"Gənclik",
		"Xaqani",
		"Xan Şuşinski",
		"Xanlar",
		"Xudu Məmmədov",
		"İbrahimpaşa Dadaşov",
		"İdris Süleymanov",
		"İlqar Abbasov",
		"İlqar İsmayılov",
		"İmran Qasımov",
		"İnqilab İsmayılov",
		"İsfəndiyar Zülalov",
		"İslam Abışov",
		"İslam Səfərli",
		"İsmayıl bəy Qutqaşınlı",
		"İsmayıl Mirzəgülov",
		"İstiqlaliyyət",
		"28 May",
		"İsgəndərov",
		"İvan Turgenev",
		"İzmir",
		"İzzət Həmidov",
		"İzzət Orucova",
		"Kamal Rəhimov",
		"Kazım Kazımzadə",
		"Kazımağa Kərimov",
		"Kərəm İsmayılov",
		"Kiçik Qala",
		"Koroğlu Rəhimov",
		"Qaçaq Nəbi",
		"Qarabağ",
		"Qədirbəyov",
		"Qəzənfər Musabəyov",
		"Qəzənfər Vəliyev",
		"Leyla Məmmədbəyova",
		"Mahmud İbrahimov",
		"Malik Məmmədov",
		"Mehdi Abbasov",
		"Mehdi Mehdizadə",
		"Məhəmməd Əmin Rəsulzadə",
		"Məhəmməd Hadi",
		"Məhəmməd Xiyabani",
		"Məhəmməd ibn Hinduşah Naxçıvani",
		"Məhsəti Gəncəvi",
		"Məmmədyarov",
		"Mərdanov qardaşları",
		"Mətləb Ağayev",
		"Məşədi Hilal",
		"Məzahir Rüstəmov",
		"Mikayıl Müşviq",
		"Mingəçevir",
		"Mirəli Qaşqay",
		"Mirəli Seyidov",
		"Mirzağa Əliyev",
		"Mirzə İbrahimov",
		"Mirzə Mənsur",
		"Mirzə Mustafayev",
		"Murtuza Muxtarov",
		"Mustafa Topçubaşov",
		"Müqtədir Aydınbəyov",
		"Müslüm Maqomayev",
		"Müzəffər Həsənov",
		"Nabat Aşurbəyova",
		"Naxçıvani",
		"Naximov",
		"Nazim İsmaylov",
		"Neapol",
		"Neftçi Qurban Abbasov",
		"Neftçilər prospekti",
		"Nəcəfbəy Vəzirov",
		"Nəcəfqulu Rəfiyev",
		"Nəriman Nərimanov",
		"Nəsirəddin Tusi",
		"Nigar Rəfibəyli",
		"Niyazi",
		"Nizami",
		"Nizami Abdullayev",
		"Nobel prospekti",
		"Novruz",
		"Novruzov qardaşları",
		"Oqtay Vəliyev",
		"Parlament",
		"Puşkin",
		"Rafiq Ağayev",
		"Ramiz Qəmbərov",
		"Rəşid Behbudov",
		"Rəşid Məcidov",
		"Ruhulla Axundov",
		"Ruslan Allahverdiyev",
		"Rüstəm Rüstəmov",
		"Tahir Bağırov",
		"Tarzan Hacı Məmmədov",
		"Tbilisi prospekti",
		"Təbriz (Bakı)",
		"Təbriz Xəlilbəyli",
		"Tofiq Məmmədov",
		"Tolstoy",
		"Sabit Orucov",
		"Sabit Rəhman",
		"Sahib Hümmətov",
		"Salatın Əsgərova",
		"Sarayevo",
		"Seyid Əzim Şirvani",
		"Seyid Şuşinski",
		"Seyidov",
		"Səməd bəy Mehmandarov",
		"Səməd Vurğun",
		"Səttar Bəhlulzadə",
		"Sona xanım Vəlixanlı",
		"Sübhi Salayev",
		"Süleyman Əhmədov",
		"Süleyman Rəhimov",
		"Süleyman Rüstəm",
		"Süleyman Sani Axundov",
		"Süleyman Vəzirov",
		"Şahin Səmədov",
		"Şamil Əzizbəyov",
		"Şamil Kamilov",
		"Şeyx Şamil",
		"Şəfayət Mehdiyev",
		"Şəmsi Bədəlbəyli",
		"Şirin Mirzəyev",
		"Şıxəli Qurbanov",
		"Şövkət Ələkbərova",
		"Ülvi Bünyadzadə",
		"Üzeyir Hacıbəyov",
		"Vasif Əliyev",
		"Vəli Məmmədov",
		"Vladislav Plotnikov",
		"Vüqar Quliyev",
		"Vunq Tau",
		"Yaqub Əliyev",
		"Yaşar Abdullayev",
		"Yaşar Əliyev",
		"Yavər Əliyev",
		"Yesenin",
		"Yəhya Hüseynov",
		"Yılmaz Axundzadə",
		"Yüsif Eyvazov",
		"Yusif Qasımov",
		"Yusif Məmmədəliyev",
		"Yusif Səfərov",
		"Yusif Vəzir Çəmənzəminli",
		"Zahid Əliyev",
		"Zahid Xəlilov",
		"Zaur Kərimov",
		"Zavod",
		"Zərgərpalan"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationBuildingNumber() {
		auto data = [
		"###'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationSecondaryAddress() {
		auto data = [
		"m. ###'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationPostcode() {
		auto data = [
		"AZ####'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationStreetSuffix() {
		auto data = [
		"küç.",
		"küçəsi",
		"prospekti",
		"pr.",
		"sahəsi",
		"sh.'"
		];
		return choice(data, this.rnd);
	}

	///
	string companyPrefix() {
		auto data = [
		"ASC",
		"MMC",
		"QSC'"
		];
		return choice(data, this.rnd);
	}


	override string companyNamePattern() {
		final switch(uniform(0, 3, this.rnd)) {
			case 0: return companyPrefix() ~ " " ~ personFemaleFirstName();
			case 1: return companyPrefix() ~ " " ~ personMaleFirstName();
			case 2: return companyPrefix() ~ " " ~ personMaleLastName();
		}
	}

	///
	override string commerceDepartment() {
		auto data = [
		"Kitablar",
		"Filmlər",
		"musiqi",
		"oyunlar",
		"Elektronika",
		"Kompyuterlər",
		"Ev",
		"садинструмент",
		"Səhiyyə",
		"gözəllik",
		"Oyuncaqlar",
		"uşaq üçün",
		"Geyim",
		"Ayyaqqabı",
		"bəzək",
		"İdman",
		"turizm",
		"Avtomobil"
		];
		return choice(data, this.rnd);
	}

	///
	override string colorHuman() {
		auto data = [
		"ala",
		"açıq bənövşəyi",
		"ağ",
		"mavi",
		"boz",
		"bənövşəyi",
		"göy rəng",
		"gümüşü",
		"kardinal",
		"narıncı",
		"qara",
		"qırmızı",
		"qəhvəyi",
		"tünd göy",
		"tünd qırmızı",
		"xlorofil",
		"yaşıl",
		"çəhrayı"
		];
		return choice(data, this.rnd);
	}


	override string dateWeekday() {
		final switch(uniform(0, 32, this.rnd)) {
			case 0: return "wide: [";
			case 1: return "Bazar";
			case 2: return "Bazar ertəsi";
			case 3: return "Çərşənbə axşamı";
			case 4: return "Çərşənbə";
			case 5: return "Cümə axşamı";
			case 6: return "Cümə";
			case 7: return "Şənbə";
			case 8: return "]";
			case 9: return "wide_context: [";
			case 10: return "воскресенье";
			case 11: return "понедельник";
			case 12: return "вторник";
			case 13: return "среда";
			case 14: return "четверг";
			case 15: return "пятница";
			case 16: return "суббота";
			case 17: return "]";
			case 18: return "abbr: ['Ba";
			case 19: return "BE";
			case 20: return "ÇA";
			case 21: return "Çə";
			case 22: return "CA";
			case 23: return "Cü";
			case 24: return "Şə']";
			case 25: return "abbr_context: ['вс";
			case 26: return "пн";
			case 27: return "вт";
			case 28: return "ср";
			case 29: return "чт";
			case 30: return "пт";
			case 31: return "сб']";
		}
	}


	override string dateMonth() {
		final switch(uniform(0, 56, this.rnd)) {
			case 0: return "wide: [";
			case 1: return "yanvar";
			case 2: return "fevral";
			case 3: return "mart";
			case 4: return "aprel";
			case 5: return "may";
			case 6: return "iyun";
			case 7: return "iyul";
			case 8: return "avqust";
			case 9: return "sentyabr";
			case 10: return "oktyabr";
			case 11: return "noyabr";
			case 12: return "dekabr";
			case 13: return "]";
			case 14: return "wide_context: [";
			case 15: return "января";
			case 16: return "февраля";
			case 17: return "марта";
			case 18: return "апреля";
			case 19: return "мая";
			case 20: return "июня";
			case 21: return "июля";
			case 22: return "августа";
			case 23: return "сентября";
			case 24: return "октября";
			case 25: return "ноября";
			case 26: return "декабря";
			case 27: return "]";
			case 28: return "abbr: [";
			case 29: return "янв.";
			case 30: return "февр.";
			case 31: return "март";
			case 32: return "апр.";
			case 33: return "май";
			case 34: return "июнь";
			case 35: return "июль";
			case 36: return "авг.";
			case 37: return "сент.";
			case 38: return "окт.";
			case 39: return "нояб.";
			case 40: return "дек.";
			case 41: return "]";
			case 42: return "abbr_context: [";
			case 43: return "янв.";
			case 44: return "февр.";
			case 45: return "марта";
			case 46: return "апр.";
			case 47: return "мая";
			case 48: return "июня";
			case 49: return "июля";
			case 50: return "авг.";
			case 51: return "сент.";
			case 52: return "окт.";
			case 53: return "нояб.";
			case 54: return "дек.";
			case 55: return "]";
		}
	}

	///
	override string phoneNumberFormats() {
		auto data = [
		"(9##)###-##-##'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string internetFreeEmail() {
		auto data = [
		"box.az",
		"mail.az",
		"gmail.com",
		"yahoo.com",
		"hotmail.com'"
		];
		return choice(data, this.rnd);
	}

	///
	override string internetDomainSuffix() {
		auto data = [
		"com",
		"az",
		"com.az",
		"info",
		"net",
		"org'"
		];
		return choice(data, this.rnd);
	}


	override string personMaleLastNamePattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "{ value: '" ~ personMaleLastName();
			case 1: return "weight: 1 }";
		}
	}

	///
	override string personMaleFirstName() {
		auto data = [
		"Anar",
		"Amid",
		"Afəl",
		"Abbas",
		"Abdulla",
		"Adil",
		"Akif",
		"Aqil",
		"Bəhram",
		"Nurlan",
		"Rafiq",
		"Tərlan",
		"Zaur",
		"Emin",
		"Emil",
		"Kamran",
		"Elnur",
		"Natiq",
		"Rəşad",
		"Rəşid",
		"Tahir",
		"Əhməd",
		"Zahir",
		"İlham",
		"İlqar",
		"Nahid",
		"Nihad",
		"Faiq",
		"İxtiyar",
		"Şəhriyar",
		"Şaiq",
		"Bəxtiyar",
		"Bəhruz",
		"Tunar",
		"Nadir"
		];
		return choice(data, this.rnd);
	}


	override string personName() {
		final switch(uniform(0, 6, this.rnd)) {
			case 0: return "{ value: '" ~ personFirstName();
			case 1: return "weight: 1 }";
			case 2: return "{ value: '" ~ personLastName() ~ " " ~ personFirstName();
			case 3: return "weight: 1 }";
			case 4: return "{ value: '" ~ personFirstName() ~ " " ~ personLastName();
			case 5: return "weight: 1 }";
		}
	}

	///
	override string personFemaleFirstName() {
		auto data = [
		"Anna",
		"Adeliya",
		"Afaq",
		"Afət",
		"Afərim",
		"Aidə",
		"Aygün",
		"Aynur",
		"Alsu",
		"Ayan",
		"Aytən",
		"Aygül",
		"Aydan",
		"Aylin",
		"Bahar",
		"Banu",
		"Bəyaz",
		"Billurə",
		"Cansu",
		"Ceyla",
		"Damla",
		"Dəniz",
		"Diana",
		"Dilarə",
		"Ella",
		"Elza",
		"Elyanora",
		"Ellada",
		"Elvira",
		"Elnarə",
		"Esmira",
		"Estella",
		"Fatimə",
		"Fəxriyyə",
		"Fərəh",
		"Fərqanə",
		"Fidan",
		"Firuzə",
		"Gövhər",
		"Günay",
		"Gülay",
		"Gülçin",
		"Gülər",
		"Gülsüm",
		"Humay",
		"Hüriyə",
		"Hülya",
		"Jalə",
		"Jasmin",
		"Kübra",
		"Ləman",
		"Lamiyə",
		"Lalə",
		"Liliya",
		"Laura",
		"Leyla",
		"Maya",
		"Mehriban",
		"Mələk",
		"Nuray",
		"Nurgün",
		"Nərgiz",
		"Nigar",
		"Ofelya",
		"Pəri",
		"Röya",
		"Səbinə",
		"Selcan",
		"Tansu",
		"Tuba",
		"Ülviyyə",
		"Ulduz",
		"Ülkər"
		];
		return choice(data, this.rnd);
	}

	///
	string personMaleLastName() {
		auto data = [
		"Əhmədov",
		"Ələkbərov",
		"Əliyev",
		"Vəliyev",
		"Soltanov",
		"Quliyev",
		"Məmmədov",
		"Xəlilov",
		"Nəzərov",
		"Rəhimov"
		];
		return choice(data, this.rnd);
	}

	///
	string personFemaleLastName() {
		auto data = [
		"Qasımova",
		"Əfəndiyeva",
		"Soltanova",
		"Abdullayeva",
		"Rəşidova",
		"Ələkbərova",
		"Əliyeva",
		"Tahirova",
		"Seyidova",
		"Vəsiyeva"
		];
		return choice(data, this.rnd);
	}


	override string personFemaleLastNamePattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "{ value: '" ~ personFemaleLastName();
			case 1: return "weight: 1 }";
		}
	}

}
