// generated by fakerjsgenerator
///
module faked.faker_zu_za;

import faked.base;


///
class Faker_zu_za : Faker {
@safe:
	import std.random;
	import std.array;
	import std.format;
	import std.conv : to;

	///
	this(int seed) {
        super(seed);
	}

	///
	override string locationCityName() {
		auto data = [
		"Polokwane",
		"eGoli",
		"Pretoria",
		"uTshwane",
		"eThekwini",
		"umGungundlovu",
		"Mbombela",
		"eKapa",
		"Stellenbosch",
		"iBhayi",
		"eMonti",
		"Kimberley",
		"Rustenburg",
		"Bloemfontein"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationState() {
		auto data = [
		"EGoli",
		"IFuleyisitata",
		"IKwaZulu-Natali",
		"ILimpopo",
		"IMpumalanga Kapa",
		"IMpumalanga",
		"INtshonalanga Kapa",
		"INyakatho Kapa",
		"INyakatho-Ntshonalanga"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationPostcode() {
		auto data = [
		"#####",
		"####'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}


	override string locationStreetPattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return personFirstName() ~ " " ~ locationStreetSuffix();
			case 1: return personLastName() ~ " " ~ locationStreetSuffix();
		}
	}

	///
	override string locationDefaultCountry() {
		auto data = [
		"South Africa'"
		];
		return choice(data, this.rnd);
	}


	override string locationCityPattern() {
		final switch(uniform(0, 1, this.rnd)) {
			case 0: return locationCityName() ~ "'";
		}
	}

	///
	override string companySuffix() {
		auto data = [
		"Pty Ltd",
		"Ltd",
		"CC'"
		];
		return choice(data, this.rnd);
	}

	///
	override string phoneNumberFormats() {
		auto data = [
		"01# ### #####",
		"02# ### #####",
		"03# ### #####",
		"04# ### #####",
		"05# ### #####",
		"0800 ### ###",
		"0860 ### ###",
		"01#########",
		"01# ########"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string cellPhoneFormats() {
		auto data = [
		"082 ### ####",
		"084 ### ####",
		"083 ### ####",
		"065 ### ####",
		"082#######",
		"082 #######"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string internetDomainSuffix() {
		auto data = [
		"co.za",
		"com",
		"org.za",
		"info",
		"net.za'"
		];
		return choice(data, this.rnd);
	}


	override string personLastNamePattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "{ value: '" ~ personLastName();
			case 1: return "weight: 1 }";
		}
	}

	///
	override string personLastName() {
		auto data = [
		"Bayeni",
		"Bengu",
		"Bhembe",
		"Bhengani",
		"Bhengu",
		"Bhuyeni",
		"Biyela",
		"Buthelezi",
		"Cebekhulu",
		"Cele",
		"Chiliza",
		"Delazy",
		"Dhlomo",
		"Dingiswayo",
		"Dlamini",
		"Dube",
		"Fuze",
		"Gabhezi",
		"Gama",
		"Gigaba",
		"Guliwe",
		"Gumede",
		"Gwacela",
		"Gwala",
		"Hlongwa",
		"Khawula",
		"Khumalo",
		"Khuzwayo",
		"Kunene",
		"Lamula",
		"Lembede",
		"Luthuli",
		"Mabhida",
		"Mabizela",
		"Maduma",
		"Magoza",
		"Malinga",
		"Maphisa",
		"Mashinini",
		"Mavundla",
		"Mbatha",
		"Mbende",
		"Mbuso",
		"Mehloluhlaza",
		"Mfeka",
		"Mfumu",
		"Mgenge",
		"Mkhatshwa",
		"Moseley",
		"Mqwebu",
		"Msibi",
		"Mthembu",
		"Mthethwa",
		"Mtolo",
		"Musi",
		"Ncusi",
		"Ndandali",
		"Ndebele",
		"Ngcolosi",
		"Ngema",
		"Ngubane",
		"Ngwazi",
		"Nhleko",
		"Nomvethe",
		"Nondlela",
		"Nonyana",
		"Nozulu",
		"Nsele",
		"Ntanzi",
		"Ntombela",
		"Nyanda",
		"Nzimande",
		"Radebe",
		"Seme",
		"Senzangakhona",
		"Shezi",
		"Sibiya",
		"Sithuli",
		"Siwele",
		"Siyaya",
		"Sokhela",
		"Sondisa",
		"Sothole",
		"Thoyana",
		"Thumbeza",
		"Thusi",
		"Tshabalala",
		"Vezi",
		"Vilakazi",
		"Wosiyane",
		"Yengwa",
		"Zondi",
		"Zondo",
		"Zubane",
		"Zuma",
		"Zungu"
		];
		return choice(data, this.rnd);
	}

	///
	override string personFirstName() {
		auto data = [
		"Amahle",
		"Anele",
		"Ayanda",
		"Ayize",
		"Bafana",
		"Bangizwe",
		"Bhekimuzi",
		"Bhekizizwe",
		"Bhekumbuso",
		"Bonginkosi",
		"Buhle",
		"Busisiwe",
		"Duduzile",
		"Dumisani",
		"Fanyana",
		"Funani",
		"Gatsha",
		"Hlengiwe",
		"Inyoni",
		"Isisa",
		"Jabulile",
		"Kagiso",
		"Kgabu",
		"Khanyisile",
		"Khethiwe",
		"Khulekani",
		"Langa",
		"Lerato",
		"Linda",
		"Liyana",
		"Lukhona",
		"Lungelo",
		"Lwandle",
		"Mandla",
		"Maphikelela",
		"Mbalienhle",
		"Mhambi",
		"Mpilo",
		"Mpumelelo",
		"Msizi",
		"Mthunzi",
		"Musawenkosi",
		"Nandi",
		"Ndleleni",
		"Ndondoloza",
		"Nhlakanipho",
		"Nkanyezi",
		"Nkosenye",
		"Nkosingiphile",
		"Nkosinhle",
		"Nkosiyabo",
		"Nofoto",
		"Nokuthula",
		"Nolwazi",
		"Nomvula",
		"Nonhlanhla",
		"Nonjabulo",
		"Nonkululeko",
		"Nozipho",
		"Ntokozo",
		"Ntombizodwa",
		"Phila",
		"Philani",
		"Phiwokwakhe",
		"Samukelisiwe",
		"Sanele",
		"Sfiso",
		"Shaka",
		"Sibongile",
		"Sibusiso",
		"Sifiso",
		"Sindisiwe",
		"Sinenhlanhla",
		"Siphephelo",
		"Siphiwe",
		"Sipho",
		"Sithembiso",
		"Siyanda",
		"Sizakele",
		"Sizani",
		"Solomon",
		"Thabisa",
		"Thadie",
		"Thamsanqa",
		"Thando",
		"Themba",
		"Thobeka",
		"Thulani",
		"Thulisile",
		"Uluthando",
		"Ulwazi",
		"Velaphi",
		"Vusumuzi",
		"Yibanathi",
		"Zanele",
		"Zenzele",
		"Zithulele",
		"Zobuhle"
		];
		return choice(data, this.rnd);
	}

	///
	override string personMaleFirstName() {
		auto data = [
		"Bonginkosi",
		"Kagiso",
		"Bhekizizwe",
		"Bhekumbuso",
		"Shaka",
		"Funani",
		"Kgabu",
		"Solomon",
		"Gatsha",
		"Langa",
		"Phila",
		"Msizi",
		"Nkosiyabo",
		"Linda",
		"Mpilo",
		"Siyanda",
		"Nkanyezi",
		"Bafana",
		"Lwandle",
		"Sfiso",
		"Thulani",
		"Thando",
		"Sanele",
		"Anele",
		"Lungelo",
		"Dumisani",
		"Bangizwe",
		"Fanyana",
		"Bhekimuzi",
		"Mandla",
		"Maphikelela",
		"Mpumelelo",
		"Mthunzi",
		"Philani",
		"Musawenkosi",
		"Nkosenye",
		"Nkosinhle",
		"Phiwokwakhe",
		"Sifiso",
		"Zithulele",
		"Sithembiso",
		"Sipho",
		"Siphiwe",
		"Sibusiso",
		"Velaphi",
		"Thamsanqa",
		"Vusumuzi",
		"Themba",
		"Zenzele",
		"Ndleleni"
		];
		return choice(data, this.rnd);
	}

	///
	override string personFemaleFirstName() {
		auto data = [
		"Amahle",
		"Ayanda",
		"Ayize",
		"Buhle",
		"Busisiwe",
		"Duduzile",
		"Hlengiwe",
		"Inyoni",
		"Isisa",
		"Jabulile",
		"Khanyisile",
		"Khethiwe",
		"Khulekani",
		"Lerato",
		"Liyana",
		"Lukhona",
		"Mbalienhle",
		"Mhambi",
		"Mthunzi",
		"Nandi",
		"Ndondoloza",
		"Nhlakanipho",
		"Nkosingiphile",
		"Nofoto",
		"Nokuthula",
		"Nolwazi",
		"Nomvula",
		"Nonhlanhla",
		"Nonjabulo",
		"Nonkululeko",
		"Nozipho",
		"Ntokozo",
		"Ntombizodwa",
		"Samukelisiwe",
		"Sibongile",
		"Sindisiwe",
		"Sinenhlanhla",
		"Siphephelo",
		"Sizakele",
		"Sizani",
		"Thabisa",
		"Thadie",
		"Thobeka",
		"Thulisile",
		"Uluthando",
		"Ulwazi",
		"Yibanathi",
		"Zanele",
		"Zobuhle"
		];
		return choice(data, this.rnd);
	}

}
