// generated by fakerjsgenerator
///
module faked.faker_ne;

import faked.base;


///
class Faker_ne : Faker {
@safe:
	import std.random;
	import std.array;
	import std.format;
	import std.conv : to;

	///
	this(int seed) {
        super(seed);
	}

	///
	override string phoneNumberFormats() {
		auto data = [
		"##-#######",
		"+977-#-#######",
		"+977########'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}

	///
	override string locationCityName() {
		auto data = [
		"Bhaktapur",
		"Biratnagar",
		"Birendranagar",
		"Birgunj",
		"Butwal",
		"Damak",
		"Dharan",
		"Gaur",
		"Gorkha",
		"Hetauda",
		"Itahari",
		"Janakpur",
		"Kathmandu",
		"Lahan",
		"Nepalgunj",
		"Pokhara"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationState() {
		auto data = [
		"Baglung",
		"Banke",
		"Bara",
		"Bardiya",
		"Bhaktapur",
		"Bhojupu",
		"Chitwan",
		"Dailekh",
		"Dang",
		"Dhading",
		"Dhankuta",
		"Dhanusa",
		"Dolakha",
		"Dolpha",
		"Gorkha",
		"Gulmi",
		"Humla",
		"Ilam",
		"Jajarkot",
		"Jhapa",
		"Jumla",
		"Kabhrepalanchok",
		"Kalikot",
		"Kapilvastu",
		"Kaski",
		"Kathmandu",
		"Lalitpur",
		"Lamjung",
		"Manang",
		"Mohottari",
		"Morang",
		"Mugu",
		"Mustang",
		"Myagdi",
		"Nawalparasi",
		"Nuwakot",
		"Palpa",
		"Parbat",
		"Parsa",
		"Ramechhap",
		"Rauswa",
		"Rautahat",
		"Rolpa",
		"Rupandehi",
		"Sankhuwasabha",
		"Sarlahi",
		"Sindhuli",
		"Sindhupalchok",
		"Sunsari",
		"Surket",
		"Syangja",
		"Tanahu",
		"Terhathum"
		];
		return choice(data, this.rnd);
	}

	///
	override string locationPostcode() {
		auto data = [
		"1####",
		"2####",
		"3####",
		"4####",
		"5####'"
		];
		return this.digitBuild(choice(data, this.rnd));
	}


	override string locationStreetPattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return personFirstName() ~ " " ~ locationStreetSuffix();
			case 1: return personLastName() ~ " " ~ locationStreetSuffix();
		}
	}

	///
	override string locationDefaultCountry() {
		auto data = [
		"Nepal'"
		];
		return choice(data, this.rnd);
	}


	override string locationCityPattern() {
		final switch(uniform(0, 1, this.rnd)) {
			case 0: return locationCityName() ~ "'";
		}
	}

	///
	override string companySuffix() {
		auto data = [
		"Pvt Ltd",
		"Group",
		"Ltd",
		"Limited'"
		];
		return choice(data, this.rnd);
	}

	///
	override string internetFreeEmail() {
		auto data = [
		"worldlink.com.np",
		"gmail.com",
		"yahoo.com",
		"hotmail.com'"
		];
		return choice(data, this.rnd);
	}

	///
	override string internetDomainSuffix() {
		auto data = [
		"np",
		"com",
		"info",
		"net",
		"org'"
		];
		return choice(data, this.rnd);
	}


	override string personLastNamePattern() {
		final switch(uniform(0, 2, this.rnd)) {
			case 0: return "{ value: '" ~ personLastName();
			case 1: return "weight: 1 }";
		}
	}

	///
	override string personLastName() {
		auto data = [
		"Adhikari",
		"Aryal",
		"Baral",
		"Basnet",
		"Bastola",
		"Basynat",
		"Bhandari",
		"Bhattarai",
		"Chettri",
		"Devkota",
		"Dhakal",
		"Dongol",
		"Ghale",
		"Gurung",
		"Gyawali",
		"Hamal",
		"Jung",
		"KC",
		"Kafle",
		"Karki",
		"Khadka",
		"Koirala",
		"Lama",
		"Limbu",
		"Magar",
		"Maharjan",
		"Niroula",
		"Pandey",
		"Pradhan",
		"Rana",
		"Raut",
		"Sai",
		"Shai",
		"Shakya",
		"Sherpa",
		"Shrestha",
		"Subedi",
		"Tamang",
		"Thapa"
		];
		return choice(data, this.rnd);
	}

	///
	override string personMaleFirstName() {
		auto data = [
		"Aarav",
		"Amit",
		"Amrit",
		"Arijit",
		"Bibek",
		"Bijay",
		"Bikash",
		"Bishal",
		"Bishnu",
		"Buddha",
		"Dipendra",
		"Gagan",
		"Ganesh",
		"Khem",
		"Krishna",
		"Nabin",
		"Niraj",
		"Nischal",
		"Padam",
		"Prabin",
		"Prakash",
		"Prashant",
		"Prem",
		"Purna",
		"Rajendra",
		"Raju",
		"Rakesh",
		"Ranjan",
		"Sagar",
		"Sandeep",
		"Sanjay",
		"Santosh",
		"Siddhartha",
		"Subash",
		"Sumeet",
		"Suraj",
		"Sushant"
		];
		return choice(data, this.rnd);
	}

	///
	override string personFemaleFirstName() {
		auto data = [
		"Ajita",
		"Amita",
		"Ashmi",
		"Asmita",
		"Bina",
		"Deepika",
		"Laxmi",
		"Manisha",
		"Nikita",
		"Pooja",
		"Rajina",
		"Ratna",
		"Sarita",
		"Shilpa",
		"Shirisha",
		"Shristi",
		"Sunita",
		"Susan"
		];
		return choice(data, this.rnd);
	}

}
