// generated by fakerjsgenerator
module faked;

///
public import faked.base;

///
public import faked.faker_af_za;

///
public import faked.faker_de;

///
public import faked.faker_de_at;

///
public import faked.faker_de_ch;

///
public import faked.faker_en_au;

///
public import faked.faker_en_au_ocker;

///
public import faked.faker_en_bork;

///
public import faked.faker_en_ca;

///
public import faked.faker_en_gb;

///
public import faked.faker_en_ie;

///
public import faked.faker_en_ind;

///
public import faked.faker_en_us;

///
public import faked.faker_en_za;

///
public import faked.faker_es;

///
public import faked.faker_fi;

///
public import faked.faker_fr;

///
public import faked.faker_fr_ca;

///
public import faked.faker_fr_ch;

///
public import faked.faker_ge;

///
public import faked.faker_hr;

///
public import faked.faker_hy;

///
public import faked.faker_id_id;

///
public import faked.faker_it;

///
public import faked.faker_ja;

///
public import faked.faker_ko;

///
public import faked.faker_lv;

///
public import faked.faker_nb_no;

///
public import faked.faker_ne;

///
public import faked.faker_nl;

///
public import faked.faker_nl_be;

///
public import faked.faker_pl;

///
public import faked.faker_pt_br;

///
public import faked.faker_pt_pt;

///
public import faked.faker_ro;

///
public import faked.faker_ru;

///
public import faked.faker_sv;

///
public import faked.faker_tr;

///
public import faked.faker_uk;

///
public import faked.faker_vi;

///
public import faked.faker_zh_cn;

///
public import faked.faker_zh_tw;

///
public import faked.faker_zu_za;

